import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { QUIZ_SEED } from "../src/data/quiz-seed";

const quote = (value: string | null | undefined) =>
  value == null ? "null" : `'${value.replaceAll("'", "''")}'`;
const values = QUIZ_SEED.map(
  (item) =>
    `(${quote(item.category)},${quote(item.difficulty)},${quote(item.question)},${quote(JSON.stringify(item.options))}::jsonb,${item.correctAnswerIndex},${quote(item.explanation)},${quote(item.sourceTitle)},${quote(item.sourceUrl)},true)`,
).join(",\n");
const sql = `-- Generated by npm run db:seed:sql\ntruncate table public.quiz_questions;\ninsert into public.quiz_questions (category,difficulty,question,options,correct_answer_index,explanation,source_title,source_url,is_active) values\n${values};\n`;
writeFileSync(resolve("supabase/seed.sql"), sql, "utf8");
console.log(`supabase/seed.sql에 ${QUIZ_SEED.length}개 문제를 기록했습니다.`);
